### ISSUE TITLE
Move first input identifier into Connection class?

### ISSUE THREAD

**Issue by rchildre3** [ra4king/CircuitSim#17]
The grey "0" on the first input Connection for various Components may be better moved to the Connection class as it is can be handled universally there, instead of by each component.

**Comment by ra4king** [comment]
The gray "0" in the muxes and decoder?

**Comment by rchildre3** [comment]
true, or perhaps an IndexedConnection class, just an idea.  Feel free to close if you think it is unnecessary.

**Comment by ra4king** [comment]
I did notice that the rendering code is too similar for those 3 classes, but I decided against doing anything about it as it's simple enough as it is.
