### ISSUE TITLE
Bug: negating inputs on logic gates

### ISSUE THREAD

**Issue by ashjtan** [ra4king/CircuitSim#37]
If I add an AND gate and change its number of inputs to anything greater than 3, it adds the options to negate the certain inputs. If I decrease the number of inputs, those negation options will stay despite those inputs not being there anymore. This is also the case for the OR gate, and likely the others.

**Comment by ra4king** [comment]
Fixed with 806002a69c454b41fe09b4f1070acbaa7afe261b
