### ISSUE TITLE
Contents of large bitsize ROM lost when reloading

### ISSUE THREAD

**Issue by necroTaxonomist** [ra4king/CircuitSim#39]
When I create a ROM with a 32-bit width, it seems the values aren't saved when the file is saved. Smaller ROMs save fine.

Steps to reproduce:
- Create a new Circuitsim file
- Add a ROM with bitsize=32 and address bits=16
- Edit the ROM's contents
- Save the file
- Restart Circuitsim
- Open the file again

**Comment by ra4king** [comment]
I was able to reproduce: all ROMs of all sizes are broken. The only reason it works is when loading existing ROMs. I don't know how I broke them. Fixed with b9b6c40e2203caea1321c37f33460a406104cf41
