### ISSUE TITLE
Loading circuit using library fails

### ISSUE THREAD

**Issue by necroTaxonomist** [ra4king/CircuitSim#49]
![image](https://user-images.githubusercontent.com/6809621/52368213-e53d6380-2a1b-11e9-8ff8-4910773bef1d.png)

If a circuit is created using an importable jar library, and is saved with elements from the library in the circuit, the circuit cannot be opened. If the elements are manually removed from the circuit, the circuit opens fine and the elements from the library are still available from the sidebar.

**Comment by necroTaxonomist** [comment]
Might be related
https://github.com/ra4king/CircuitSim/issues/50

**Comment by ra4king** [comment]
Most likely the library isn't found. I notice now I don't throw an error if the library path (in the .sim file) doesn't exist. I've improved that with 492b4741d2ba1b3bc2ed3a6a0f839866ef0c8f53
