### ISSUE TITLE
Alternate RAM data interface

### ISSUE THREAD

**Issue by anott3** [ra4king/CircuitSim#51]
Logisim/Brandonsim offered a variant of RAM that had separate load and store ports. While it's technically possible to implement the datapath and stuff with the current version (and tbh how I did it way back when), it was nice being able to recommend the separate load/store port variant as it was more simpler and intuitive to figure out.

**Comment by anott3** [comment]
If I'm able to figure out the code and everything, I'm def down to take a stab at this

**Comment by ra4king** [comment]
Done with #52
