### ISSUE TITLE
Constant value bigger than bitsize

### ISSUE THREAD

**Issue by Dallas-D** [ra4king/CircuitSim#55]
Constants let you set a value that is bigger than what should be possible with its bit size. For example, you can set a constant to be 100 with a bit size of 1. The last bits are the only ones shown. For example, 100 is "01100100" in binary, so a bit size of 3 will display "100".

**Comment by ra4king** [comment]
I remember there was a reason why I didn't correct the input to the modulo of the bitsize. I'll play around with doing it again and see if I remember why.

**Comment by ra4king** [comment]
Lol years later cleaning up the CircuitSim bugs. I remember now: sometimes you might accidentally change the bitsize and you'd lose the large value. I think it's fine as is.
