### ISSUE TITLE
Crash when file browser is open on edit RAM contents (macOS)

### ISSUE THREAD

**Issue by mubtAAhij** [ra4king/CircuitSim#61]
I've recently come across an issue where when a RAM module exists on the circuit, and you right click on it>Edit Contents>Load from File, and then switch windows to another open application while the file browser is open, CircuitSim will crash. I attached the crash log; my OS is macOS Mojave 10.14.6.
[crash_log.txt](https://github.com/ra4king/CircuitSim/files/3693692/crash_log.txt)

**Comment by ra4king** [comment]
Looks to be a JavaFX bug: https://bugs.openjdk.java.net/browse/JDK-8211304

It's fixed in JavaFX 11.0.2+ and 12+. Looks like I need to make CircuitSim working with the new module system in Java 11+
