### ISSUE TITLE
Feature Request: Allow Binary/Hex values to be entered for constants

### ISSUE THREAD

**Issue by farzamtn** [ra4king/CircuitSim#65]
Right now when you make a constant and put the base in binary, you still have to enter the value in decimal and it will convert it to binary for you. It might be nice to have the option to enter the value in binary as well

**Comment by ra4king** [comment]
Hex values are already supported if you prefix with 0x. I can add binary support with 0b prefix.

**Comment by ra4king** [comment]
I committed 75339b167e95df49a0f799ab760b5b7556450689 for binary support. I realize after testing this that the input field changes to decimal when you finish inputting it. Let me see if I can fix this.

**Comment by ra4king** [comment]
Commit 0665bb2b9f0e311641b843496d548cd26921f2a4 preserves the input base used in both the UI and save file.
