### ISSUE TITLE
the Text in the misc didn't support multi language

### ISSUE THREAD

**Issue by codeoflin** [ra4king/CircuitSim#68]
![图片](https://user-images.githubusercontent.com/45932283/95942979-2738c280-0e17-11eb-925d-f5d7662fd966.png)

**Comment by ra4king** [comment]
Thanks for reporting this! I was able to reproduce this, and it seems the font used (Deja Vu Sans Mono) doesn't support Chinese. I went back to the site I downloaded it from and it has the "Chinese" tag on it.

Unfortunately this means ditching my font... I'll investigate.

**Comment by codeoflin** [comment]
Thanks for replay,I'll wait for it (^_^)

**Comment by ra4king** [comment]
Unfortunately changing the font now means breaking everyone's saved sim files. I have to keep the current font and live with the consequences. Sorry! :(
