### ISSUE TITLE
Remove polarity of transistors

### ISSUE THREAD

**Issue by thayes46** [ra4king/CircuitSim#69]
By professor request, removing the polarity attribute of transistors to allow them to act as just a bridge aligns significantly more with how transistors are explained. While manufactured transistors do have an optimal direction of current, for the classes that circuitsim is used it doesn't add much to content and adds confusion in some places.

**Comment by ausbin** [comment]
Hopefully #72 addressed this. Polarity isn't removed but at least they are in sync with Patt & Patel
