### ISSUE TITLE
NOT peers have a negate input property

### ISSUE THREAD

**Issue by ausbin** [ra4king/CircuitSim#83]
If you place a NOT gate, you can negate its input:

![image](https://user-images.githubusercontent.com/431756/210503352-691fe20b-9c2b-4278-8184-71e7a7998c06.png)

However, the bubble is not drawn, and it does not appear to change the behavior of the gate:

![image](https://user-images.githubusercontent.com/431756/210503404-88a5cc0c-4c1b-4c82-8b40-f131a4ac52d1.png)

However, it does shift the gate over as if there was a bubble. Below is with the mystery property set to false:

![image](https://user-images.githubusercontent.com/431756/210503501-e4205577-aac0-4013-9bae-859a3f2d07b6.png)

Normally I would try to make myself useful and fix this, but I got stuck on the following:

1. It's tempting to check if there are 1 inputs in GatePeer, but in the future we could add a gate that takes 1 input but for which a bubbled input is useful (no clue what that would be)
2. I'm not sure if (1) would change the x/y of the gate, breaking existing circuits with the mystery property set to true (you would know this better)

**Comment by ra4king** [comment]
How did I miss this... fixed in 199e5ad. Thanks!
